### PR TITLE
Option to adjust the space above OverflowMenus

### PR DESCRIPTION
**Pull request by dvbeelen**
Adds the option to adjust the spaceAboveMenu for OverflowMenus. If no value for this option is provided, the spaceAboveMenu will keep it's default value of 0.

This change should resolve the issue raised here:
https://github.com/vonovak/react-navigation-header-buttons/issues/103

### CODE REVIEW

**Review by vonovak — CHANGES_REQUESTED** [review]
hello, thank you for the PR! This looks all right to me. Just two points:

1) the new prop is only considered for android, is that intended?
2) please add readme documentation for this, thank you!

thanks again!

**Comment by dvbeelen** [comment]
The change is indeed only intended for android. On iOS the overflow menus are rendered from the bottom up, so setting space above it shouldn't be necessary. 

I've also added some readme documentation!

**Comment by dvbeelen** [comment]
@vonovak I've made the changes you requested, could you please approve this PR?

**Comment by vonovak** [comment]
thanks for the PR!

**Pull request merged**
