### PR TITLE
Adding disabled state

### PR DESCRIPTION
**Pull request by ricsam**

### CODE REVIEW

**Comment by vonovak** [comment]
I have taken a slightly different approach which is now available in v2, please let me know if that works well for you. Thanks!

**Comment by vonovak** [comment]
closing as this is now shipped with v2, and can be used [like this](https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/navbar-buttons-demo/screens/UsageDisabled.js)

**Comment by mifozski** [comment]
@vonovak the link you provided is invalid. Can you please update or provide another one? I didn't the information on how make the button disabled in the readme.

**Comment by vonovak** [comment]
Hi, take a look at https://github.com/vonovak/react-navigation-header-buttons/blob/master/example/screens/UsageDisabled.tsx

**Pull request closed without merging**
